buildscript: scripts/build
postinstall: scripts/postinstall.sh
pip:
 - gunicorn
dependencies:
 - nginx
 - postgresql-server-dev-all
 - libpq-dev
 - postgresql
 - rabbitmq-server
 - libxml2-dev
 - libxslt1-dev
 - python-dev
