language: python
python:
  - "2.7"
before_script:
  - ./setuptests.sh
install:
  - "pip install -r requirements.txt --use-wheel"
  - "pip install -r requirements-dev.txt --use-wheel"
script:
  - flake8 .
  - py.test . --ds=control.testsettings
