language: python
python:
  - "2.6"
  - "2.7"
before_script:
  - ./setuptests.sh
install:
  - "pip install git+https://github.com/westerncapelabs/django-snappy-vumi-bouncer.git@feature/issue-1-basic-implementation"
  - "pip install -r requirements.txt --use-wheel"
  - "pip install -r requirements-dev.txt --use-wheel"
script:
  - python manage.py syncdb --noinput
  - python manage.py migrate
  - python manage.py test
